#!/usr/bin/env bash
# Launch a single t3.medium EC2 for Kafka adapter smoke tests.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/instances.env"

AWS_REGION="${AWS_REGION:-us-west-2}"
KEY_NAME="${AWS_KEY_NAME:?Set AWS_KEY_NAME to your EC2 key pair name}"
SSH_USER="${SSH_USER:-ubuntu}"
INSTANCE_TYPE="${KAFKA_SMOKE_INSTANCE_TYPE:-t3.medium}"

AMI_ID="${AWS_AMI_ID:-$(aws ec2 describe-images --region "$AWS_REGION" \
  --owners 099720109477 \
  --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
            "Name=state,Values=available" \
  --query 'sort_by(Images,&CreationDate)[-1].ImageId' --output text)}"

MY_IP="$(curl -sf https://checkip.amazonaws.com || echo "0.0.0.0")"

SG_NAME="photon-kafka-smoke-$(date +%Y%m%d)"
VPC_ID="$(aws ec2 describe-vpcs --region "$AWS_REGION" \
  --filters Name=isDefault,Values=true \
  --query 'Vpcs[0].VpcId' --output text)"

SG_ID="$(aws ec2 create-security-group --region "$AWS_REGION" \
  --group-name "$SG_NAME" --description "Photon Kafka smoke host" \
  --vpc-id "$VPC_ID" --query GroupId --output text)"

aws ec2 authorize-security-group-ingress --region "$AWS_REGION" --group-id "$SG_ID" \
  --ip-permissions \
  "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${MY_IP}/32,Description=ssh}]" \
  "IpProtocol=tcp,FromPort=9092,ToPort=9092,UserIdGroupPairs=[{GroupId=${SG_ID}}]" \
  >/dev/null

IID="$(aws ec2 run-instances --region "$AWS_REGION" \
  --image-id "$AMI_ID" \
  --instance-type "$INSTANCE_TYPE" \
  --key-name "$KEY_NAME" \
  --security-group-ids "$SG_ID" \
  --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=photon-kafka-smoke},{Key=Project,Value=photon-kafka-smoke}]" \
  --query 'Instances[0].InstanceId' --output text)"

echo "Waiting for ${IID}..."
aws ec2 wait instance-running --region "$AWS_REGION" --instance-ids "$IID"

PRIVATE_IP="$(aws ec2 describe-instances --region "$AWS_REGION" --instance-ids "$IID" \
  --query 'Reservations[0].Instances[0].PrivateIpAddress' --output text)"
PUBLIC_IP="$(aws ec2 describe-instances --region "$AWS_REGION" --instance-ids "$IID" \
  --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)"

cat >"$ENV_FILE" <<EOF
# Generated by provision.sh
AWS_REGION=${AWS_REGION}
SSH_USER=${SSH_USER}
SSH_KEY_PATH=\${SSH_KEY_PATH:-\$HOME/.ssh/${KEY_NAME}.pem}
SECURITY_GROUP_ID=${SG_ID}
INSTANCE_SMOKE=${IID}
SMOKE_IP=${PRIVATE_IP}
SMOKE_PUBLIC_IP=${PUBLIC_IP}
EOF

echo "Wrote ${ENV_FILE}"
cat "$ENV_FILE"
