#!/usr/bin/env bash
# Export PHOTON_KAFKA_* for smoke host (localhost broker).
set -euo pipefail

# AWS/CI test transport key (not for production).
export PHOTON_TRANSPORT_KEY="${PHOTON_TRANSPORT_KEY:-cGhvdG9uLWRldi10cmFuc3BvcnQta2V5LTMyYnl0ZXM=}"

export PHOTON_KAFKA_BROKERS="${PHOTON_KAFKA_BROKERS:-127.0.0.1:9092}"
export PHOTON_KAFKA_TOPIC_PREFIX="${PHOTON_KAFKA_TOPIC_PREFIX:-photon}"
export PHOTON_KAFKA_RETENTION="${PHOTON_KAFKA_RETENTION:-15m}"
export PHOTON_KAFKA_REPLICAS="${PHOTON_KAFKA_REPLICAS:-1}"
export PHOTON_KAFKA_REPLAY_CURSOR="${PHOTON_KAFKA_REPLAY_CURSOR:-stream_seq}"
export PHOTON_KAFKA_SYNC_ACK="${PHOTON_KAFKA_SYNC_ACK:-1}"
export PHOTON_KAFKA_MAX_INFLIGHT="${PHOTON_KAFKA_MAX_INFLIGHT:-1}"
export PHOTON_KAFKA_TOPIC_SHARDS="${PHOTON_KAFKA_TOPIC_SHARDS:-1}"

echo "PHOTON_KAFKA_BROKERS=${PHOTON_KAFKA_BROKERS}"
echo "PHOTON_KAFKA_TOPIC_SHARDS=${PHOTON_KAFKA_TOPIC_SHARDS}"
