#!/usr/bin/env bash
# Export PHOTON_FLUVIO_* for local single-node Fluvio lab.
set -euo pipefail

export PHOTON_FLUVIO_ENDPOINT="${PHOTON_FLUVIO_ENDPOINT:-127.0.0.1:9103}"
export PHOTON_FLUVIO_TOPIC_PREFIX="${PHOTON_FLUVIO_TOPIC_PREFIX:-photon}"
export PHOTON_FLUVIO_RETENTION="${PHOTON_FLUVIO_RETENTION:-15m}"
export PHOTON_FLUVIO_REPLICAS="${PHOTON_FLUVIO_REPLICAS:-1}"
export PHOTON_FLUVIO_REPLAY_CURSOR="${PHOTON_FLUVIO_REPLAY_CURSOR:-stream_seq}"
export PHOTON_FLUVIO_SYNC_ACK="${PHOTON_FLUVIO_SYNC_ACK:-1}"
export PHOTON_FLUVIO_MAX_INFLIGHT="${PHOTON_FLUVIO_MAX_INFLIGHT:-1}"
export PHOTON_FLUVIO_TOPIC_SHARDS="${PHOTON_FLUVIO_TOPIC_SHARDS:-1}"

echo "PHOTON_FLUVIO_ENDPOINT=${PHOTON_FLUVIO_ENDPOINT}"
echo "PHOTON_FLUVIO_TOPIC_PREFIX=${PHOTON_FLUVIO_TOPIC_PREFIX}"
echo "PHOTON_FLUVIO_TOPIC_SHARDS=${PHOTON_FLUVIO_TOPIC_SHARDS}"
