#!/usr/bin/env bash
# Launch multi-EC2 broker fleet + bench host. Requires AWS CLI and SSH key pair.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/instances.env"

AWS_REGION="${AWS_REGION:-us-west-2}"
KEY_NAME="${AWS_KEY_NAME:?Set AWS_KEY_NAME to your EC2 key pair name}"
SSH_USER="${SSH_USER:-ubuntu}"
BROKER_TYPE="${BROKER_INSTANCE_TYPE:-t3.medium}"
BENCH_TYPE="${BENCH_INSTANCE_TYPE:-c6i.large}"
BENCH_COUNT="${BENCH_COUNT:-4}"
HARDWARE="${PHOTON_BENCH_HARDWARE:-aws-c6i-large}"

if [[ "$BENCH_COUNT" -lt 1 || "$BENCH_COUNT" -gt 8 ]]; then
  echo "BENCH_COUNT must be 1..8 (got ${BENCH_COUNT})" >&2
  exit 1
fi

# Ubuntu 22.04 LTS amd64 (update via SSM if AMI drifts)
AMI_ID="${AWS_AMI_ID:-$(aws ec2 describe-images --region "$AWS_REGION" \
  --owners 099720109477 \
  --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
            "Name=state,Values=available" \
  --query 'sort_by(Images,&CreationDate)[-1].ImageId' --output text)}"

MY_IP="$(curl -sf https://checkip.amazonaws.com || echo "0.0.0.0")"

SG_NAME="photon-broker-fleet-$(date +%Y%m%d)"
VPC_ID="$(aws ec2 describe-vpcs --region "$AWS_REGION" \
  --filters Name=isDefault,Values=true \
  --query 'Vpcs[0].VpcId' --output text)"

SG_ID="$(aws ec2 create-security-group --region "$AWS_REGION" \
  --group-name "$SG_NAME" --description "Photon NATS broker fleet" \
  --vpc-id "$VPC_ID" --query GroupId --output text)"

aws ec2 authorize-security-group-ingress --region "$AWS_REGION" --group-id "$SG_ID" \
  --ip-permissions \
  "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${MY_IP}/32,Description=ssh}]" \
  "IpProtocol=tcp,FromPort=22,ToPort=22,UserIdGroupPairs=[{GroupId=${SG_ID},Description=intra-fleet-ssh}]" \
  "IpProtocol=tcp,FromPort=4222,ToPort=4224,UserIdGroupPairs=[{GroupId=${SG_ID}}]" \
  "IpProtocol=tcp,FromPort=6222,ToPort=6222,UserIdGroupPairs=[{GroupId=${SG_ID}}]" \
  "IpProtocol=tcp,FromPort=8222,ToPort=8224,UserIdGroupPairs=[{GroupId=${SG_ID}}]" \
  >/dev/null

launch() {
  local name="$1"
  local itype="$2"
  aws ec2 run-instances --region "$AWS_REGION" \
    --image-id "$AMI_ID" \
    --instance-type "$itype" \
    --key-name "$KEY_NAME" \
    --security-group-ids "$SG_ID" \
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${name}},{Key=Project,Value=photon-broker-fleet}]" \
    --query 'Instances[0].InstanceId' --output text
}

echo "Launching instances in ${AWS_REGION}..."
IID_SINGLE="$(launch photon-broker-single "$BROKER_TYPE")"
IID_B1="$(launch photon-broker-1 "$BROKER_TYPE")"
IID_B2="$(launch photon-broker-2 "$BROKER_TYPE")"
IID_B3="$(launch photon-broker-3 "$BROKER_TYPE")"
BENCH_IIDS=()
for i in $(seq 1 "$BENCH_COUNT"); do
  BENCH_IIDS+=("$(launch "photon-bench-${i}" "$BENCH_TYPE")")
done

IDS=("$IID_SINGLE" "$IID_B1" "$IID_B2" "$IID_B3" "${BENCH_IIDS[@]}")
echo "Waiting for instances to run..."
aws ec2 wait instance-running --region "$AWS_REGION" --instance-ids "${IDS[@]}"

describe_ip() {
  local iid="$1"
  local field="$2"
  aws ec2 describe-instances --region "$AWS_REGION" --instance-ids "$iid" \
    --query "Reservations[0].Instances[0].${field}" --output text
}

cat >"$ENV_FILE" <<EOF
# Generated by provision.sh — source before orchestration scripts
AWS_REGION=${AWS_REGION}
SSH_USER=${SSH_USER}
SSH_KEY_PATH=\${SSH_KEY_PATH:-\$HOME/.ssh/${KEY_NAME}.pem}
HARDWARE=${HARDWARE}
SECURITY_GROUP_ID=${SG_ID}

INSTANCE_BROKER_SINGLE=${IID_SINGLE}
BROKER_SINGLE_IP=$(describe_ip "$IID_SINGLE" PrivateIpAddress)
BROKER_SINGLE_PUBLIC_IP=$(describe_ip "$IID_SINGLE" PublicIpAddress)

INSTANCE_BROKER_1=${IID_B1}
BROKER_1_IP=$(describe_ip "$IID_B1" PrivateIpAddress)
BROKER_1_PUBLIC_IP=$(describe_ip "$IID_B1" PublicIpAddress)

INSTANCE_BROKER_2=${IID_B2}
BROKER_2_IP=$(describe_ip "$IID_B2" PrivateIpAddress)
BROKER_2_PUBLIC_IP=$(describe_ip "$IID_B2" PublicIpAddress)

INSTANCE_BROKER_3=${IID_B3}
BROKER_3_IP=$(describe_ip "$IID_B3" PrivateIpAddress)
BROKER_3_PUBLIC_IP=$(describe_ip "$IID_B3" PublicIpAddress)

BENCH_COUNT=${BENCH_COUNT}
EOF

for i in $(seq 1 "$BENCH_COUNT"); do
  iid="${BENCH_IIDS[$((i - 1))]}"
  {
    echo "INSTANCE_BENCH_${i}=${iid}"
    echo "BENCH_${i}_IP=$(describe_ip "$iid" PrivateIpAddress)"
    echo "BENCH_${i}_PUBLIC_IP=$(describe_ip "$iid" PublicIpAddress)"
  } >>"$ENV_FILE"
done

# Backward compat: BENCH_1 is the primary bench host.
{
  echo "INSTANCE_BENCH=${BENCH_IIDS[0]}"
  echo "BENCH_IP=$(describe_ip "${BENCH_IIDS[0]}" PrivateIpAddress)"
  echo "BENCH_PUBLIC_IP=$(describe_ip "${BENCH_IIDS[0]}" PublicIpAddress)"
} >>"$ENV_FILE"

echo "Wrote ${ENV_FILE}"
cat "$ENV_FILE"
echo ""
echo "Next: bootstrap brokers and bench (see README.md)"
